name: Build and Publish
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests in Docker
        run: docker build -f Dockerfile.test .
  
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Docker
        run: |
          docker build \
            --build-arg GOOS=${{ matrix.os }} \
            --build-arg GOARCH=${{ matrix.arch }} \
            -t openapi-converter-builder:${{ matrix.os }}-${{ matrix.arch }} .
      
      - name: Extract binary from Docker
        run: |
          EXT=""
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            EXT=.exe
          fi
          docker create --name temp-container openapi-converter-builder:${{ matrix.os }}-${{ matrix.arch }}
          mkdir -p dist
          docker cp temp-container:/root/openapi-converter${EXT} ./dist/openapi-converter-${{ matrix.os }}-${{ matrix.arch }}${EXT}
          docker rm temp-container
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-converter-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/openapi-converter-*
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      
      - name: Prepare release assets
        run: |
          cd dist
          for dir in */; do
            cd "$dir"
            for file in openapi-converter-*; do
              mv "$file" "../$file"
            done
            cd ..
            rm -rf "$dir"
          done
          ls -la
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: dist/openapi-converter-*
          body: |
            ## OpenAPI Converter ${{ steps.version.outputs.version }}
            
            ### Installation
            
            #### CLI Binary
            Download the appropriate binary for your platform from the assets below.
            
            #### Go Install
            ```bash
            go install github.com/nimling/openapi-converter@${{ steps.version.outputs.version }}
            ```
            
            #### GitHub Action
            ```yaml
            - uses: nimling/openapi-converter@${{ steps.version.outputs.version }}
              with:
                openapi-file: spec.yml
                docs-dir: output
                common-prefix: api
                write-introduction: true
            ```
            
            ### Full Changelog
            https://github.com/${{ github.repository }}/commits/${{ steps.version.outputs.version }}
          draft: false
          prerelease: false